export const chabadData = [
    {
      tool: "תנור אפייה",
      aliases: ["תנור", "אפייה"],
      process: "ניקוי יסודי, המתנה של 24 שעות, הפעלה בחום מקסימלי למשך שעה",
      sources: ["אגרות משה אורח חיים א, קכד"],
      chumrot: ["רבים נוהגים לא להשתמש בתנור לפסח אלא לכסותו בנייר כסף"],
      emoji: "🔥",
    },
    {
      tool: "מיקרוגל",
      aliases: ["מיקרו"],
      process: "ניקוי יסודי, הרתחת כוס מים עם סבון למשך 10 דקות",
      sources: ["הליכות שלמה פסח פרק ג"],
      chumrot: ["יש הנוהגים להשתמש רק עם כיסוי כפול"],
      emoji: "📻",
    },
    {
      tool: "סכין",
      aliases: ["סכו״ם", "מזלג", "כף"],
      process: "הגעלה ברותחים שלוש פעמים, כולל הידית",
      sources: ["שולחן ערוך אורח חיים תנא, ג"],
      chumrot: ["יש הנוהגים לקנות סכו״ם מיוחד לפסח"],
      emoji: "🍴",
    },
    {
      tool: "כלי חרס",
      aliases: ["חרסינה", "קרמיקה", "פורצלן"],
      process: "אין אפשרות להכשיר",
      sources: ["שולחן ערוך אורח חיים תנא, א"],
      chumrot: [],
      notes: "יש לקנות כלים חדשים או להשתמש בכלים המיוחדים לפסח",
      emoji: "🏺",
    },
  ];