export const ashkenazData = [
    {
      tool: "מחבת",
      aliases: ["פנצ׳ר", "טיגון"],
      process: "ליבון קל (עד שקש יישרף מצדו השני)",
      sources: ["משנה ברורה תנא, כח"],
      chumrot: ["יש הנוהגים ליבון חמור"],
      emoji: "🍳",
    },
    {
      tool: "כוס זכוכית",
      aliases: ["כוסות", "גביע"],
      process: "הגעלה שלוש פעמים במים רותחים",
      sources: ["רמ״א אורח חיים תנא, כו"],
      chumrot: [],
      emoji: "🥛",
    },
    {
      tool: "סכין",
      aliases: ["סכו״ם", "מזלג", "כף"],
      process: "הגעלה ברותחים שלוש פעמים, כולל הידית",
      sources: ["שולחן ערוך אורח חיים תנא, ג"],
      chumrot: ["יש הנוהגים לקנות סכו״ם מיוחד לפסח"],
      emoji: "🍴",
    },
    {
      tool: "שיש",
      aliases: ["משטח עבודה", "משטח מטבח"],
      process: "ניקוי יסודי, עירוי מים רותחים, כיסוי בנייר כסף או משטח אחר",
      sources: ["משנה ברורה תנא, קטו"],
      chumrot: [],
      emoji: "🧱",
    },
    {
      tool: "כלי חרס",
      aliases: ["חרסינה", "קרמיקה", "פורצלן"],
      process: "אין אפשרות להכשיר",
      sources: ["שולחן ערוך אורח חיים תנא, א"],
      chumrot: [],
      notes: "יש לקנות כלים חדשים או להשתמש בכלים המיוחדים לפסח",
      emoji: "🏺",
    },
  ];